# This workflow uses GitHub actions to run Eggplant DAI tests

name: DAI_Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository files 
        uses: actions/checkout@v2
        with:
          url: https://assets.eggplantsoftware.com/EggplantRunner/eggplant-runner-Windows-25.2.0+5.exe
          target: DAIRunner.exe
      - name: Source Branch Name
        run: echo ${{ github.ref }}

      - name: Run DAI Tests
        run: |
              echo Running DAI tests
              C:\Users\vijayalaxmi.kummari\Downloads\eggplant-runner-Windows-25.2.0+5.exe "http://localhost:8000/" "f66c0e16-090a-4a42-8573-7679f50bd90c" --client-id=client:dai:api:integration:bde01020-f928-4f19-b8db-13f8e0aa9a40 --client-secret=9oiyJ0CYdRPoXeWkYXKvoOnfzwGwzMpQ
                echo DAI tests complete.
